# Form implementation generated from reading ui file 'layout.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(443, 308)
        font = QtGui.QFont()
        font.setPointSize(12)
        Dialog.setFont(font)
        self.gridLayoutWidget = QtWidgets.QWidget(parent=Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 421, 291))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.umowa = QtWidgets.QCheckBox(parent=self.gridLayoutWidget)
        self.umowa.setObjectName("umowa")
        self.gridLayout.addWidget(self.umowa, 4, 0, 1, 1)
        self.zapisz = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.zapisz.setObjectName("zapisz")
        self.gridLayout.addWidget(self.zapisz, 4, 1, 1, 1)
        self.imie = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.imie.setObjectName("imie")
        self.gridLayout.addWidget(self.imie, 0, 1, 1, 1)
        self.nazwisko = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.nazwisko.setObjectName("nazwisko")
        self.gridLayout.addWidget(self.nazwisko, 1, 1, 1, 1)
        self.telefon = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.telefon.setObjectName("telefon")
        self.gridLayout.addWidget(self.telefon, 2, 1, 1, 1)
        self.pesel = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.pesel.setObjectName("pesel")
        self.gridLayout.addWidget(self.pesel, 3, 1, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_3.setText(_translate("Dialog", "pesel"))
        self.label_4.setText(_translate("Dialog", "Numer telefonu"))
        self.label_2.setText(_translate("Dialog", "Nazwisko"))
        self.label.setText(_translate("Dialog", "Imie"))
        self.umowa.setText(_translate("Dialog", "Umowa o prace"))
        self.zapisz.setText(_translate("Dialog", "Zapisz"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
